#120179 Обновить зависимости библиотеки
AISGorod/AISGorod.AspNetCore.Authentication.Esia pull request #25
Opened 2024-07-02 10:10 UTC by vad7043

2024-07-02 10:35 UTC, CryFromTheHeart commented
LGTM

2024-08-05 19:07 UTC, vladdy-moses requested changes

2024-08-05 19:07 UTC, vladdy-moses commented on samples/EsiaNet8Sample/Program.cs
> +        options.Mnemonic = "RIAS-HCS-ULYANOVSK";
Не-а =) TESTSYS + rebase, чтобы не видно было, что за мнемоника у нас

2024-08-05 19:07 UTC, vladdy-moses commented on samples/EsiaSample/OpensslEsiaSigner.cs
> +    private const string CRT_FILE = @"/home/vv_tokarev/esia.pem";
Уж тогда лучше `/home/username/esia....`

2024-08-05 19:07 UTC, vladdy-moses commented on samples/EsiaSample/Startup.cs
> +                options.Mnemonic = "RIAS-HCS-ULYANOVSK";
TESTSYS

2024-08-05 19:07 UTC, vladdy-moses commented on src/EsiaDefaults.cs
> +        public const string AUTHENTICATION_SCHEME = "Esia";
Я бы вернул константы. В исходниках aspnetcore именно UpperCamelCase используется, и ИМХО это лучше, чем C-шный стиль

2024-08-05 19:07 UTC, vladdy-moses commented on src/EsiaDefaults.cs
> +        public const string DISPLAY_NAME = "Госуслуги (ЕСИА)";
Тут тоже UpperCamelCase

2024-08-05 19:07 UTC, vladdy-moses commented on src/EsiaDefaults.cs
> +        public const string ENABLES_SCOPES_PROPERTIES_KEY = "Esia.EnabledScopes";
Тут тоже UpperCamelCase

2024-08-05 19:07 UTC, vladdy-moses commented on src/AISGorod.AspNetCore.Authentication.Esia.csproj
> +		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
Предлагаю зависимости написать в виде `[8.0.6.9)` и `[13.0.3,14)`, чтобы поsemverовски было

2024-08-05 19:07 UTC, vladdy-moses commented on src/AISGorod.AspNetCore.Authentication.Esia.csproj
> +		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
Аналогично с зависимостями. Только надо посмотреть, можем ли бы сделать сразу `[6.0.11,8)` для OpenIdConnect. Возможно можем

2024-08-05 19:07 UTC, vladdy-moses commented on src/EsiaRestService.cs
> +            var responseJson = JObject.Parse(responseStr);
revert

2024-08-05 19:07 UTC, vladdy-moses commented on src/OpenIdConnectOptionsBuilder.cs
>      }
Ну не знаю... Я бы вернул =)
А то получается, что верхний `if` состоит из 3х строк, а скобок не имеет.

2024-08-12 06:00 UTC, vladdy-moses approved these changes

2024-08-12 06:01 UTC, merged