#128345 Добавить пакеты с реализацией подписи от BouncyCastle и CryptoPro [C#]
AISGorod/AISGorod.AspNetCore.Authentication.Esia pull request #32
Opened 2024-12-06 13:28 UTC by vad7043

2024-12-09 10:20 UTC, vladdy-moses requested changes
Немного правок, а так всё хорошо!

Единственное, что не увидел - это исправление сборки (github actions).
Но я так и не понял, как сделать, чтобы сборка в форках тоже работала..)

2024-12-09 10:20 UTC, vladdy-moses commented on src/Esia.CryptoPro/Esia.CryptoPro.csproj
> +      <PackageReference Include="CryptoPro.Security.Cryptography.Xml" Version="2024.11.19" />
А тут можно сделать `>=2024.11.19`?
Так сказать, на будущее =)

2024-12-09 10:20 UTC, vladdy-moses commented on src/Esia/EsiaExtensions.cs
> +
ooops, пробельчики.😺

2024-12-09 10:20 UTC, vladdy-moses commented on src/Esia/Options/BouncyCastleOptions.cs
> +    public string? CertFilePath { get; set; }
Есть смысл делать эти свойства необязательными?
Как будто их вообще в будущем можно пометить как `required {get;init;}`

2024-12-09 10:20 UTC, vladdy-moses commented on src/Esia/Options/CryptoProOptions.cs
> +    public string? CertThumbprint { get; set; }
Сертификат как будто тоже надо обязательным.

 Пин - нет

2024-12-09 10:34 UTC, vad7043 commented on src/Esia.CryptoPro/Esia.CryptoPro.csproj
> +      <PackageReference Include="CryptoPro.Security.Cryptography.Xml" Version="2024.11.19" />
да, сделал и исполняемый файл тоже поменял, чтобы последнюю версию загружал

2024-12-09 11:49 UTC, vladdy-moses approved these changes

2024-12-10 07:42 UTC, vladdy-moses approved these changes

2024-12-10 07:43 UTC, merged