#128964 Актуализированы методы OIDC ЕСИА [C#]
AISGorod/AISGorod.AspNetCore.Authentication.Esia pull request #35
Opened 2024-12-18 09:45 UTC by vad7043

2024-12-18 16:32 UTC, vladdy-moses requested changes

2024-12-18 16:32 UTC, vladdy-moses commented on samples/EsiaNet8Sample/Controllers/HomeController.cs
> +        var scopeList = string.IsNullOrEmpty(scopes) ? ["openid"] : scopes.Split(' ');
Тут как будто надо откатить =(

Это для теста было =)

2024-12-18 16:32 UTC, vladdy-moses commented on samples/EsiaNet8Sample/Program.cs
> +        options.Scope = [];
Хе =) Как будто тоже надо откатить

2024-12-18 16:32 UTC, vladdy-moses commented on samples/EsiaNet8Sample/Program.cs
> -
А куда пропал?(

2024-12-18 16:32 UTC, vladdy-moses commented on samples/EsiaNet8Sample/Program.cs
> +            bouncyCastleOptions.KeyFilePath = "/home/username/esia.key";
Внезапное изменение =) Предлагаю тоже откатить

2024-12-18 16:32 UTC, vladdy-moses commented on src/Esia.BouncyCastle/Esia.BouncyCastle.csproj
> +	</ItemGroup>
Форматирование уехало =(

На гихабе видно из-за того, что тут 1 таб === 8 пробелов

2024-12-18 16:32 UTC, vladdy-moses commented on src/Esia.CryptoPro/CryptoProEsiaSigner.cs
> +            "1.2.643.7.1.1.1.1" => CpHashAlgorithmName.GOST3411_2012_256,
Слушай, а в библиотечке криптопро нет никаких констант под эти oId-ы?

Предполагаю, что что-то есть. Но кто же знает...

2024-12-18 16:32 UTC, vladdy-moses commented on src/Esia/EsiaExtensions.cs
> +    internal static string SignData(this IEsiaSigner? esiaSigner, string concatenatedString)
А может тогда сразу метод подписи угнать в `IEsiaSigner`?

Тогда будет минус непонятный extension =)

2024-12-18 16:32 UTC, vladdy-moses commented on src/Esia/Options/EsiaOptions.cs
>      public PathString SignedOutCallbackPath { get; set; } = "/signout-esia";
А тут норм?

2024-12-19 09:19 UTC, vad7043 commented on samples/EsiaNet8Sample/Program.cs
> -
Он по умолчанию задаётся в EsiaOptions

2024-12-19 09:32 UTC, vad7043 commented on src/Esia.CryptoPro/CryptoProEsiaSigner.cs
> +            "1.2.643.7.1.1.1.1" => CpHashAlgorithmName.GOST3411_2012_256,
нет или я не нашёл, создал свой класс с константами

2024-12-19 09:39 UTC, vad7043 commented on src/Esia/EsiaExtensions.cs
> +    internal static string SignData(this IEsiaSigner? esiaSigner, string concatenatedString)
Вообще убрал этот метод, теперь в Sign передаётся просто строка для подписания

2024-12-19 09:46 UTC, vad7043 commented on src/Esia/Options/EsiaOptions.cs
>      public PathString SignedOutCallbackPath { get; set; } = "/signout-esia";
да, потому что это свойство находится в OpenIdConnectOptions, а CallBackPath в RemoteAuthenticationOptions

2024-12-19 10:13 UTC, vladdy-moses commented on samples/EsiaNet8Sample/Program.cs
> -
Но тут он был для примера, что так можно сделать =)

2024-12-19 11:52 UTC, vladdy-moses approved these changes

2024-12-19 11:53 UTC, merged